#!/usr/bin/env bash

function bootstrap {
  local shome="${_vagrant_shell_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  bundle _1.10.6_ install --path vendor/bundle
  "$shome/script/test"
}

bootstrap

